<?php
/**
 * Created by PhpStorm.
 */

namespace frontend\controllers;

use frontend\models\Repo;
use Yii;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;

class AjaxController extends AppController
{
    /**
     * @param \yii\base\Action $action
     * @return bool
     * @throws NotFoundHttpException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (!$this->getRequest()->isAjax || !$this->getRequest()->isPost) {
            throw new NotFoundHttpException();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionSearchRepo(): string
    {
        $query = $this->getRequest()->post('query');

        $datas = Repo::findOne(['q' => $query]);

        if (empty($datas)) {
            // Запрашиваем данные
            $response = Yii::$app->repoHelper->searchRepo($query);

            if ($response) {
                // Сохраняем данные в БД
                $datas = Yii::$app->repoHelper->saveRepo($query, Json::encode($response));
            }
        }

        return $this->renderAjax('search-repo', [
            'datas' => Yii::$app->repoHelper->getItems($datas->result),
        ]);
    }
}
